"""Initial migration.

Revision ID: 3020cfe92e07
Revises: 
Create Date: 2024-06-18 08:46:48.492149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3020cfe92e07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citas')
    op.drop_table('pacientes')
    op.drop_table('pruebapacientes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pruebapacientes',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('pacientes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lastname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('branch', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('rut_cc', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('document_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('citas',
    sa.Column('cita_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('series_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('type_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('status_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('owner_id', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_action_by', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('type_label', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('status_label', mysql.VARCHAR(length=85), nullable=True),
    sa.PrimaryKeyConstraint('cita_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
