"""empty message

Revision ID: 760b525574dd
Revises: 
Create Date: 2024-07-05 14:53:48.854542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '760b525574dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('pruebapacientes')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.alter_column('type_id',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('status_id',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('owner_id',
               existing_type=mysql.MEDIUMINT(display_width=8, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('last_action_by',
               existing_type=mysql.MEDIUMINT(display_width=8, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=mysql.SMALLINT(display_width=5, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=85),
               nullable=True)
        batch_op.alter_column('admin_group_id',
               existing_type=mysql.SMALLINT(display_width=5, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('legacyid',
               existing_type=mysql.CHAR(length=16),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('isdefault',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.String(length=16),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('document_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.alter_column('autoassign',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('requires_approval',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False)
        batch_op.alter_column('allow_multiday_reservations',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('max_participants',
               existing_type=mysql.MEDIUMINT(display_width=8, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('legacyid',
               existing_type=mysql.CHAR(length=16),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('allow_calendar_subscription',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('resource_type_id',
               existing_type=mysql.MEDIUMINT(display_width=8, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('status_id',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('enable_check_in',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('allow_display',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.SmallInteger(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index('public_id')

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.MEDIUMINT(display_width=8, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('group_id',
               existing_type=mysql.SMALLINT(display_width=5, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.MEDIUMINT(display_width=8, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('homepageid',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('date_created',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('last_modified',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('status_id',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('legacyid',
               existing_type=mysql.CHAR(length=16),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('allow_calendar_subscription',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('default_schedule_id',
               existing_type=mysql.SMALLINT(display_width=5, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('document_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'CC'"))
        batch_op.drop_index('organization')
        batch_op.drop_index('public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('public_id', ['public_id'], unique=True)
        batch_op.create_index('organization', ['organization'], unique=True)
        batch_op.alter_column('document_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'CC'"))
        batch_op.alter_column('default_schedule_id',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(display_width=5, unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('allow_calendar_subscription',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('legacyid',
               existing_type=sa.String(length=16),
               type_=mysql.CHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('status_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('last_modified',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('date_created',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('homepageid',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(display_width=8, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(display_width=5, unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(display_width=8, unsigned=True),
               existing_nullable=False)

    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index('public_id', ['public_id'], unique=True)
        batch_op.alter_column('allow_display',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('enable_check_in',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status_id',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('resource_type_id',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(display_width=8, unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('allow_calendar_subscription',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('legacyid',
               existing_type=sa.String(length=16),
               type_=mysql.CHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('max_participants',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(display_width=8, unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('allow_multiday_reservations',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('requires_approval',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('autoassign',
               existing_type=sa.SmallInteger(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('document_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.alter_column('isdefault',
               existing_type=sa.String(length=16),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('legacyid',
               existing_type=sa.String(length=16),
               type_=mysql.CHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('admin_group_id',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(display_width=5, unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=85),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(display_width=5, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('citas', schema=None) as batch_op:
        batch_op.alter_column('last_action_by',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(display_width=8, unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(display_width=8, unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('status_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('type_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    op.create_table('pruebapacientes',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('role_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('role_level', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
