"""empty message

Revision ID: 9d50053d95a4
Revises: 
Create Date: 2024-06-20 13:56:47.843553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d50053d95a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('citas')
    op.drop_table('user_groups')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index('public_id')

    op.drop_table('resources')
    op.drop_table('pruebapacientes')
    op.drop_table('roles')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.MEDIUMINT(display_width=8, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('homepageid',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('date_created',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('last_modified',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('status_id',
               existing_type=mysql.TINYINT(display_width=3, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('legacyid',
               existing_type=mysql.CHAR(length=16),
               type_=sa.String(length=16),
               existing_nullable=True)
        batch_op.alter_column('allow_calendar_subscription',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('default_schedule_id',
               existing_type=mysql.SMALLINT(display_width=5, unsigned=True),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index('organization')
        batch_op.drop_index('public_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('public_id', ['public_id'], unique=True)
        batch_op.create_index('organization', ['organization'], unique=True)
        batch_op.alter_column('default_schedule_id',
               existing_type=sa.Integer(),
               type_=mysql.SMALLINT(display_width=5, unsigned=True),
               existing_nullable=True)
        batch_op.alter_column('allow_calendar_subscription',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('legacyid',
               existing_type=sa.String(length=16),
               type_=mysql.CHAR(length=16),
               existing_nullable=True)
        batch_op.alter_column('status_id',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               existing_nullable=False)
        batch_op.alter_column('last_modified',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('date_created',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('homepageid',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=3, unsigned=True),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=mysql.MEDIUMINT(display_width=8, unsigned=True),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.alter_column('phone',
               existing_type=sa.BigInteger(),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    op.create_table('roles',
    sa.Column('role_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('role_level', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('pruebapacientes',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('lname', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('resources',
    sa.Column('resource_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=85), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_info', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('min_duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('min_increment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('unit_cost', mysql.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('autoassign', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('requires_approval', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('allow_multiday_reservations', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('max_participants', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('min_notice_time_add', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_notice_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('image_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('schedule_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('legacyid', mysql.CHAR(length=16), nullable=True),
    sa.Column('admin_group_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('public_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('allow_calendar_subscription', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('sort_order', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('resource_type_id', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('status_id', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('resource_status_reason_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('buffer_time', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('enable_check_in', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('auto_release_minutes', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('allow_display', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('credit_count', mysql.DECIMAL(unsigned=True, precision=7, scale=2), nullable=True),
    sa.Column('peak_credit_count', mysql.DECIMAL(unsigned=True, precision=7, scale=2), nullable=True),
    sa.Column('min_notice_time_update', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('min_notice_time_delete', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified', mysql.DATETIME(), nullable=True),
    sa.Column('additional_properties', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index('public_id', ['public_id'], unique=True)

    op.create_table('user_groups',
    sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('citas',
    sa.Column('cita_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('series_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.DATETIME(), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('type_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('status_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('owner_id', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('last_action_by', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('type_label', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('status_label', mysql.VARCHAR(length=85), nullable=True),
    sa.PrimaryKeyConstraint('cita_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
