"""empty message

Revision ID: b059a2697624
Revises: 
Create Date: 2024-06-06 10:52:00.157479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b059a2697624'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('organization')
        batch_op.drop_index('public_id')

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index('public_id')

    op.drop_table('resources')
    op.drop_table('user_groups')
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('timezone')
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('timezone', mysql.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    op.create_table('user_groups',
    sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'user_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('resources',
    sa.Column('resource_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=85), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('contact_info', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('min_duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('min_increment', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_duration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('unit_cost', mysql.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('autoassign', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('requires_approval', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('allow_multiday_reservations', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('max_participants', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('min_notice_time_add', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('max_notice_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('image_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('schedule_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('legacyid', mysql.CHAR(length=16), nullable=True),
    sa.Column('admin_group_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('public_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('allow_calendar_subscription', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('sort_order', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('resource_type_id', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('status_id', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('resource_status_reason_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('buffer_time', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('enable_check_in', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('auto_release_minutes', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('color', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('allow_display', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('credit_count', mysql.DECIMAL(unsigned=True, precision=7, scale=2), nullable=True),
    sa.Column('peak_credit_count', mysql.DECIMAL(unsigned=True, precision=7, scale=2), nullable=True),
    sa.Column('min_notice_time_update', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('min_notice_time_delete', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('date_created', mysql.DATETIME(), nullable=True),
    sa.Column('last_modified', mysql.DATETIME(), nullable=True),
    sa.Column('additional_properties', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('resource_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index('public_id', ['public_id'], unique=True)

    op.create_table('roles',
    sa.Column('role_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('role_level', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.MEDIUMINT(display_width=8, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('fname', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('lname', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=85), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=85), nullable=False),
    sa.Column('salt', mysql.VARCHAR(length=85), nullable=False),
    sa.Column('organization', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('position', mysql.VARCHAR(length=85), server_default=sa.text("'Cardio IB IPS'"), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=85), nullable=True),
    sa.Column('timezone', mysql.VARCHAR(length=85), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('homepageid', mysql.TINYINT(display_width=3, unsigned=True), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('date_created', mysql.DATETIME(), nullable=False),
    sa.Column('last_modified', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('lastlogin', mysql.DATETIME(), nullable=True),
    sa.Column('status_id', mysql.TINYINT(display_width=3, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('legacyid', mysql.CHAR(length=16), nullable=True),
    sa.Column('legacypassword', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('public_id', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('allow_calendar_subscription', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('default_schedule_id', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=True),
    sa.Column('credit_count', mysql.DECIMAL(precision=7, scale=2), server_default=sa.text('0.00'), nullable=True),
    sa.Column('terms_date_accepted', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8_general_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('public_id', ['public_id'], unique=True)
        batch_op.create_index('organization', ['organization'], unique=True)

    # ### end Alembic commands ###
